version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.10"

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

python:
  # Install our python package before building the docs
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
