{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}
{% set name = data.get('name') %}
{% set version = data.get('version') %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ../

build:
  noarch: python
  number: 0
  entry_points:
    - kom = kelp_o_matic.cli:cli
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python ~=3.7,<3.11
    - pip
  run:
    - python ~=3.7,<3.11
    - numpy ~=1.16
    - pytorch ~=1.10
    - rasterio ~=1.2
    - torchvision ~=0.11
    - tqdm ~=4.62
    - typer ~=0.4

test:
  imports:
    - kelp_o_matic
    - kelp_o_matic.data
    - kelp_o_matic.geotiff_io
  commands:
    - kom --help

about:
  home: "https://github.com/hakaiInstitute/kelp-o-matic"
  license: MIT
  license_file: LICENSE.txt
  summary: "Hakai Segment Tool for GeoTiff RPAS Imagery"
  doc_url: "https://kelp-o-matic.readthedocs.io"
  dev_url: "https://github.com/hakaiInstitute/kelp-o-matic"

extra:
  recipe-maintainers:
    - tayden
