package:
  name: kelp-o-matic
  version: {{ environ.get('GIT_DESCRIBE_TAG', '0.0.0') }}

source:
  git_url: ../

build:
  noarch: python
  number: 0
  entry_points:
    - kom = kelp_o_matic.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ~=3.9,<4.0
    - poetry-core
    - pip
  run:
    - python ~=3.9,<4.0
    - numpy ~=1.24.2
    - pytorch ~=2.0.0, !=2.0.1
    - rasterio ~=1.3.7
    - torchvision ~=0.15.0
    - tqdm ~=4.65.0
    - typer ~=0.9.0
  run_constrained:
    - pytorch-cuda ~= 11.7

test:
  imports:
    - kelp_o_matic
    - kelp_o_matic.data
    - kelp_o_matic.geotiff_io
  commands:
    - pip check
    - kom --help
  requires:
    - pip

about:
  home: "https://github.com/hakaiInstitute/kelp-o-matic"
  license: MIT
  license_file: LICENSE.txt
  summary: "Hakai Segment Tool for GeoTiff RPAS Imagery"
  doc_url: "https://kelp-o-matic.readthedocs.io"
  dev_url: "https://github.com/HakaiInstitute/kelp-o-matic"

extra:
  recipe-maintainers:
    - tayden
