package:
  name: kelp-o-matic
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'v0.0.0')[1:] }}

source:
  git_url: ../

build:
  noarch: python
  number: 0
  entry_points:
    - kom = kelp_o_matic.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9, <3.12
    - poetry-core
    - pip
  run:
    - python ~=3.9, <3.12
    - numpy >=1.24.2, <2
    - pytorch >=2.1.0, <3
    - fsspec
    - rasterio >=1.3.7, <2
    - rich >=13.5, <14
    - torchvision ~=0.16.1
    - typer ~=0.9.0
    - packaging >=24.1, <25
  run_constrained:
    - pytorch-cuda >=11.8

test:
  imports:
    - kelp_o_matic
    - kelp_o_matic.geotiff_io
  commands:
    - pip check
    - kom --help
  requires:
    - pip

about:
  home: https://github.com/HakaiInstitute/kelp-o-matic
  summary: Segmentation Tools for Remotely Sensed RPAS Imagery
  license: MIT
  license_file: LICENSE.txt
  doc_url: "https://kelp-o-matic.readthedocs.io"
  dev_url: "https://github.com/HakaiInstitute/kelp-o-matic"

extra:
  recipe-maintainers:
    - tayden
